'use client';
import Link from 'next/link';
import { ArrowUpRight, Utensils, Wallet, Users, ShoppingBag, CreditCard } from 'lucide-react';
import { useData, Heading, Loading } from '../components/common';
import { useUser } from '../components/shell';
import { money } from '../lib/api';
type Report={date:string;sales:{currency:string;_sum:{totalAmount:string};_count:number}[];payments:{receivedCurrency:string;method:string;_sum:{receivedAmount:string}}[];served:number;subscriptions:number;pendingPayments:number};
export default function Dashboard(){const user=useUser();if(!user?.permissions.includes('reports.read'))return <RoleDashboard/>;return <ReportsDashboard/>;}
function RoleDashboard(){const permissions=useUser()?.permissions??[];const shortcuts:[string,string,string,typeof Wallet][]=[];if(permissions.includes('sales.create'))shortcuts.push(['/pos','Ouvrir la caisse','Démarrer une vente',CreditCard]);if(permissions.includes('orders.read'))shortcuts.push(['/orders','Commandes','Suivre les commandes',ShoppingBag]);if(permissions.includes('kitchen.read'))shortcuts.push(['/kitchen','Cuisine','Voir les préparations en cours',Utensils]);if(permissions.includes('delivery.read'))shortcuts.push(['/delivery','Livraisons','Consulter les missions affectées',ShoppingBag]);if(permissions.includes('stock.read'))shortcuts.push(['/stock','Stocks','Vérifier les niveaux et réceptions',ShoppingBag]);if(permissions.includes('clients.read'))shortcuts.push(['/clients','Clients','Rechercher un client',Users]);if(permissions.includes('cash.read'))shortcuts.push(['/cash','Ma caisse','Consulter ma session de caisse',Wallet]);if(permissions.includes('users.read'))shortcuts.push(['/users','Utilisateurs','Gérer les accès attribués',Users]);return <><Heading title="Votre espace de travail" subtitle="Accédez rapidement aux tâches autorisées pour votre rôle."/><section className="grid">{shortcuts.map(([href,title,description,Icon])=><Link className="card role-shortcut" href={href} key={href}><Icon size={21} color="#ae6c37"/><h2>{title}</h2><p className="muted small">{description}</p><span className="role-link">Ouvrir <ArrowUpRight size={15}/></span></Link>)}</section>{shortcuts.length===0&&<p className="empty">Aucune fonction n’est attribuée à ce compte. Contactez votre responsable.</p>}</>;}
function ReportsDashboard(){const q=useData<Report>('/reports');return <><Heading title="Votre restaurant, en un regard" subtitle="L’essentiel de votre activité, aujourd’hui à Kinshasa."><Link className="primary" href="/pos">Ouvrir la caisse <ArrowUpRight size={16}/></Link></Heading><section className="hero"><div><p className="eyebrow" style={{color:'#efae35'}}>BONJOUR, L’ÉQUIPE JAMI FOOD</p><h2>Chaque repas compte.<br/>Chaque opération aussi.</h2><p>De l’accueil des étudiants à la dernière clôture, gardez le fil du service et prenez soin de votre restaurant.</p><Link className="primary" href="/kitchen">Voir les commandes en cuisine →</Link></div><div className="hero-aside"><span>NOTRE ENGAGEMENT</span><strong>100 %</strong><span>au service du campus</span></div></section><Loading loading={q.isLoading} error={q.error}/><section className="grid">{[[ShoppingBag,'Ventes du jour',q.data?.sales.map(s=>money(s._sum.totalAmount,s.currency)).join(' + ')||'—','Ventes directes confirmées'],[Wallet,'Paiements en attente',q.data?.pendingPayments??'—','À vérifier avant encaissement'],[Utensils,'Commandes servies',q.data?.served??'—','Remises enregistrées aujourd’hui'],[Users,'Abonnements actifs',q.data?.subscriptions??'—','Droits ouverts sur la période']].map(([Icon,title,value,sub])=>{const I=Icon as typeof Wallet;return <article className="card" key={String(title)}><I size={20} color="#ae6c37"/><p className="muted small">{String(title)}</p><div className="metric">{String(value)}</div><span className="muted small">{String(sub)}</span></article>;})}</section><div className="two-columns section"><section className="card"><h2>Raccourcis du service</h2><div className="list">{[['/clients','Accueillir un client','Fiches, recherche et identification'],['/subscriptions','Gérer les abonnements','Formules et droits nominatifs'],['/stock','Contrôler les stocks','Réceptions, pertes et inventaires']].map(([href,title,text])=><Link className="item" key={href} href={href}><span><strong>{title}</strong><br/><small className="muted">{text}</small></span><ArrowUpRight size={18}/></Link>)}</div></section><section className="card"><h2>Contrôle & clôtures</h2><p className="muted">Consultez les clôtures, comparez le comptage physique aux mouvements et retrouvez leur validation.</p><Link href="/cash" className="secondary">Consulter les clôtures →</Link><div className="section"><h3>Des comptes lisibles</h3><p className="muted small">Les ventes, les paiements et les repas prépayés restent distincts. Les montants en USD et en CDF sont suivis séparément.</p></div></section></div></>;}
