'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ProductImage } from '../../components/product-image';
import { Feedback, Heading, Loading, useAction, useData } from '../../components/common';
import { useUser } from '../../components/shell';
import { api, money } from '../../lib/api';

type CatalogProduct = { id:string; name:string; imageUrl:string; category:{code:string;label:string}; stockMode:string; stockItem:{active:boolean;quantity:string}|null; stockQuantity:string; price:{amount:string;currency:string}; optionGroups:{id:string;name:string;type:string;required:boolean;minSelections:number;maxSelections:number;options:{id:string;name:string;priceDelta:string;currency:string;linkedProduct?:{id:string;name:string;active:boolean;available:boolean;stockMode:string;stockItem:{active:boolean;quantity:string}|null;stockQuantity:string}|null}[]}[] };
type Client = {id:string;firstName:string;lastName:string;ulcNumber:string|null;phone:string|null;category:{code:string;label:string};hasPickupToday?:boolean;subscriptions?:{id:string;status:string;startsOn:string;endsOn:string;planName:string}[]};
type Line = {id:string;quantity:string;lineTotal:string;productSnapshot:{name?:string};variantsSnapshot?:Record<string,string>|null;supplementsSnapshot?:{name:string;unitPrice:string;quantity:number}[]|null};
type Payment = {id:string;status:string;method:string;amountDue:string};
type Order = {id:string;number:string;status:string;sourceChannel:'POS'|'WHATSAPP';serviceCode:string|null;totalAmount:string;commercialTotal:string;coveredAmount:string;currency:string;clientId?:string|null;coverageReason?:string|null;createdAt?:string;handoverAt?:string|null;receiptCopy?:string|null;remainingAmount?:string;paidAmount?:string;payments?:Payment[];items?:Line[];client?:Client|null;pendingPayment?:Payment|null;subscriptionName?:string|null};
type SubscriberInfo = {client:Omit<Client,'subscriptions'> & {subscriptions:{id:string;status:string;startsOn:string;endsOn:string;balance:string;currency:string;planVersion:{services:unknown;plan:{name:string}}}[]};orders:Order[]};
type CashSession = {id:string;openedAt:string;status:string;openingUsd:string;openingCdf:string;cashRegister:{label:string;code:string}}|null;
type CartLine = {key:string;product:CatalogProduct;quantity:number;selections:Record<string,string[]>};
type Stage = 'HOME'|'SUBSCRIBER'|'DIRECT';
type PaymentResult = {id:string;status:string;amountDue?:string;changeAmount:string;changeCurrency:string|null;remainingAmount:string;orderStatus:string;method?:string};
const serviceLabel:Record<string,string>={BREAKFAST:'Petit-déjeuner',LUNCH:'Déjeuner',DINNER:'Dîner',MAIN:'Repas principal'};
function statusLabel(status:string){return ({ACTIVE:'ACTIF',SCHEDULED:'PLANIFIÉ',PENDING_PAYMENT:'PAIEMENT EN ATTENTE',SUSPENDED:'SUSPENDU',EXPIRED:'EXPIRÉ',CANCELLED:'ANNULÉ'} as Record<string,string>)[status]??status;}
function cartTotal(cart:CartLine[]){return cart.reduce((all,line)=>{const additions=Object.entries(line.selections).flatMap(([groupId,ids])=>ids.map(id=>Number(line.product.optionGroups.find(group=>group.id===groupId)?.options.find(option=>option.id===id)?.priceDelta??0))).reduce((a,b)=>a+b,0);return all+(Number(line.product.price.amount)+additions)*line.quantity;},0);}
export default function Pos(){
  const [stage,setStage]=useState<Stage>('HOME');
  const [query,setQuery]=useState('');
  const [debounced,setDebounced]=useState('');
  const [subscriber,setSubscriber]=useState<Client|null>(null);
  const [service,setService]=useState<'BREAKFAST'|'LUNCH'|'DINNER'>('LUNCH');
  const [commercialCategory,setCommercialCategory]=useState<string|null>(null);
  const [cart,setCart]=useState<CartLine[]>([]);
  const [customizing,setCustomizing]=useState<CatalogProduct|null>(null);
  const [selection,setSelection]=useState<Record<string,string[]>>({});
  const [order,setOrder]=useState<Order|null>(null);
  const [payment,setPayment]=useState<PaymentResult|null>(null);
  const [method,setMethod]=useState('CASH');
  const [received,setReceived]=useState('');
  const [reference,setReference]=useState('');
  const [completed,setCompleted]=useState(false);
  const [lastReceipt,setLastReceipt]=useState<Order|null>(null);
  const printed=useRef('');
  const action=useAction();
  const user=useUser();
  const session=useData<CashSession>('/cash');
  const results=useQuery({queryKey:['pos-subscriber-search',debounced],queryFn:()=>api<Client[]>(`/orders/subscriber-search?q=${encodeURIComponent(debounced)}&limit=10`),enabled:debounced.length>=2});
  const profile=useQuery({queryKey:['pos-subscriber',subscriber?.id],queryFn:()=>api<SubscriberInfo>(`/orders/pos-subscriber/${subscriber!.id}`),enabled:!!subscriber?.id});
  const catalog=useData<{categoryCode:string;products:CatalogProduct[]}>(subscriber?`/orders/pos-catalog?categoryCode=${encodeURIComponent(subscriber.category.code)}&currency=CDF`:'/orders/pos-catalog?currency=CDF');
  const categoryCode=subscriber?.category.code??catalog.data?.categoryCode;
  const totalIndicatif=useMemo(()=>cartTotal(cart),[cart]);
  const productCategories=useMemo(()=>[...new Map((catalog.data?.products??[]).map(product=>[product.category.code,product.category])).values()],[catalog.data]);
  const due=payment?.remainingAmount??order?.remainingAmount??(order?String(Math.max(0,Number(order.totalAmount)-Number(order.coveredAmount)-Number(order.paidAmount??0))):'0');
  useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(query.trim()),250);return()=>window.clearTimeout(timer);},[query]);
  useEffect(()=>{setCart([]);setOrder(null);setPayment(null);setCompleted(false);setCommercialCategory(null);},[subscriber?.id,service]);
  function reset(){setOrder(null);setPayment(null);setCart([]);setSubscriber(null);setQuery('');setDebounced('');setReference('');setReceived('');setCompleted(false);setCommercialCategory(null);setStage('HOME');}
  function printTicket(ticket:Order,returnHome:boolean){setOrder(ticket);setLastReceipt(ticket);setCompleted(true);window.setTimeout(()=>{window.print();if(returnHome)reset();},120);}
  function chooseProduct(product:CatalogProduct){if(product.optionGroups.length){setCustomizing(product);setSelection({});}else setCart(lines=>[...lines,{key:crypto.randomUUID(),product,quantity:1,selections:{}}]);}
  function addCustomized(){if(!customizing)return;const valid=customizing.optionGroups.every(group=>{const count=selection[group.id]?.length??0;return count>=Math.max(group.minSelections,group.required?1:0)&&count<=group.maxSelections;});if(!valid){action.run(async()=>{throw new Error('Choisissez les options obligatoires du produit.');});return;}setCart(lines=>[...lines,{key:crypto.randomUUID(),product:customizing,quantity:1,selections:selection}]);setCustomizing(null);setSelection({});}
  async function createSale(){if(!cart.length||!session.data)throw new Error('Aucune caisse active ne vous est affectée. Contactez le Gestionnaire.');if(!categoryCode)throw new Error('La catégorie de tarification comptoir n’est pas configurée.');const created=await api<Order>('/orders',{...(subscriber?{clientId:subscriber.id}:{}),categoryCode,serviceCode:service,serviceMode:'TAKEAWAY',currency:'CDF',items:cart.map(line=>({productId:line.product.id,quantity:line.quantity,selections:line.selections}))});setOrder({...created,client:subscriber,clientId:subscriber?.id??null,sourceChannel:'POS',createdAt:new Date().toISOString(),remainingAmount:String(Math.max(0,Number(created.totalAmount)-Number(created.coveredAmount))),paidAmount:'0'});setPayment(null);setMethod('CASH');setReference('');setReceived(String(Math.max(0,Number(created.totalAmount)-Number(created.coveredAmount))));}
  async function handover(current:Order){if(!session.data)throw new Error('Aucune caisse active ne vous est affectée. Contactez le Gestionnaire.');const result=await api<{receiptUrl:string}>(`/orders/${current.id}/handover`,{cashSessionId:session.data.id},crypto.randomUUID());const ticket=await api<Order>(result.receiptUrl);printTicket(ticket,true);}
  async function submitPayment(){if(!order||!session.data)throw new Error('Aucune caisse active ne vous est affectée. Contactez le Gestionnaire.');if(method!=='CASH'&&!reference.trim())throw new Error('La référence de paiement est obligatoire.');const result=await api<PaymentResult>(`/orders/${order.id}/payments`,{cashSessionId:session.data.id,method,receivedAmount:received||due,receivedCurrency:'CDF',...(method==='CASH'?{}:{externalReference:reference.trim()})});setPayment(result);setOrder(current=>current?{...current,paidAmount:String(Number(current.paidAmount??0)+Number(result.amountDue??0)),remainingAmount:result.remainingAmount}:null);if(result.status==='CONFIRMED'&&Number(result.remainingAmount)===0){if(order.clientId){await handover({...order,remainingAmount:'0'});}else{const ticket=await api<Order>(`/orders/${order.id}/receipt`);printTicket(ticket,true);}}}
  async function chooseWhatsAppOrder(row:Order){setOrder({...row,client:subscriber,sourceChannel:'WHATSAPP'});setPayment(null);setReceived(row.remainingAmount??'0');setMethod('CASH');setStage('SUBSCRIBER');}
  async function addPickupExtras(){if(!order||!session.data||!cart.length)throw new Error('Sélectionnez un extra.');await api<Order>(`/orders/${order.id}/extras`,{cashSessionId:session.data.id,items:cart.map(line=>({productId:line.product.id,quantity:line.quantity,selections:line.selections}))});setCart([]);const refreshed=await api<SubscriberInfo>(`/orders/pos-subscriber/${subscriber!.id}`);profile.refetch();const updated=refreshed.orders.find(row=>row.id===order.id);if(updated){setOrder({...updated,client:subscriber});setReceived(updated.remainingAmount??'0');}}
  return <>
    <div className="no-print"><Heading title="JAMI FOOD POS" subtitle={`${user?.firstName??''} ${user?.lastName??''} · Service comptoir et retrait abonné.`}/>
      <section className="card pos-cash-session"><div className="toolbar"><div><h2>Ma caisse</h2>{session.data?<small className="success">ACTIVE · {session.data.cashRegister.label} · {session.data.cashRegister.code} · ouverte {new Intl.DateTimeFormat('fr-CD',{dateStyle:'short',timeStyle:'short'}).format(new Date(session.data.openedAt))}</small>:<small className="error">Aucune caisse active ne vous est affectée. Contactez le Gestionnaire.</small>}</div><strong className="badge">{session.data?.status??'NON AFFECTÉE'}</strong></div></section>
      <Feedback {...action}/>
      {stage==='HOME'?<><section className="card pos-home"><h2>Choisir une opération</h2><div className="pos-home-actions"><button className="primary" type="button" onClick={()=>{setStage('SUBSCRIBER');setSubscriber(null);setOrder(null);}}>ABONNÉ</button><button className="secondary" type="button" onClick={()=>{setStage('DIRECT');setSubscriber(null);setOrder(null);}}>VENTE DIRECTE</button></div></section>{lastReceipt&&<section className="card"><h2>Dernier ticket</h2><p>{lastReceipt.number} · {lastReceipt.client?`${lastReceipt.client.firstName} ${lastReceipt.client.lastName}`:'Vente directe'} · {money(lastReceipt.totalAmount,lastReceipt.currency)}</p><button type="button" className="secondary" onClick={()=>void action.run(async()=>{const duplicate=await api<Order>(`/orders/${lastReceipt.id}/receipt?duplicate=true`);setLastReceipt(duplicate);setOrder(duplicate);setCompleted(true);window.setTimeout(()=>{window.print();setOrder(null);setCompleted(false);},100);},'Duplicata prêt à imprimer.')}>RÉIMPRIMER · DUPLICATA</button></section>}</>:<>
        <button type="button" className="secondary" onClick={reset}>← Retour à l’accueil POS</button>
        {stage==='SUBSCRIBER'&&<section className="card"><h2>Servir un abonné</h2>{!subscriber?<><label>Rechercher par nom, prénom, matricule ou téléphone<input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Nom de l’abonné" /></label><Loading loading={results.isLoading&&debounced.length>=2} error={results.error}/>{debounced.length>=2&&<div className="list">{results.data?.map(client=><button key={client.id} type="button" className="item" onClick={()=>{setSubscriber(client);setQuery('');}}><span><strong>{client.firstName} {client.lastName}</strong><br/><small className="muted">{client.ulcNumber??client.phone??client.category.label}</small></span>{client.hasPickupToday&&<strong className="success">COMMANDE À RETIRER</strong>}</button>)}</div>}</>:<>
          <div className="item"><span><strong>{subscriber.firstName} {subscriber.lastName}</strong><br/><small>{subscriber.ulcNumber??subscriber.phone??''}</small></span><button className="secondary" type="button" onClick={()=>setSubscriber(null)}>Changer d’abonné</button></div>
          <Loading loading={profile.isLoading} error={profile.error}/>
          {profile.data?.client.subscriptions.map(item=><p key={item.id} className={item.status==='ACTIVE'?'success':'muted'}><strong>{item.planVersion.plan.name} · {statusLabel(item.status)}</strong><br/><small>{new Intl.DateTimeFormat('fr-CD',{dateStyle:'short'}).format(new Date(item.startsOn))} → {new Intl.DateTimeFormat('fr-CD',{dateStyle:'short'}).format(new Date(item.endsOn))}</small></p>)}
          {profile.data?.orders.map(row=><div key={row.id} className="item"><span><strong>Commande à retirer · {serviceLabel[row.serviceCode??'']??row.serviceCode}</strong><br/><small>{row.number} · {row.items?.map(line=>`${line.productSnapshot.name??'Article'} × ${line.quantity}`).join(' · ')}</small><br/><small>Commercial {money(row.commercialTotal,row.currency)} · Couvert {money(row.coveredAmount,row.currency)} · Payé {money(row.paidAmount??'0',row.currency)} · Reste {money(row.remainingAmount??'0',row.currency)}</small></span><button className="primary" type="button" onClick={()=>void chooseWhatsAppOrder(row)}>Ouvrir / retirer</button></div>)}
          {!order&&<><h3>Choisir le service demandé</h3><div className="pos-payment-methods">{(['BREAKFAST','LUNCH','DINNER'] as const).map(value=><button key={value} className={service===value?'pos-payment-choice selected':'pos-payment-choice'} onClick={()=>setService(value)} type="button">{serviceLabel[value]}</button>)}</div></>}
        </>}</section>}
        {(stage==='DIRECT'||(stage==='SUBSCRIBER'&&subscriber&&!order))&&<section className="card"><h2>{stage==='DIRECT'?'Vente directe anonyme':'Repas demandé'}</h2><div className="pos-payment-methods">{(['BREAKFAST','LUNCH','DINNER'] as const).map(value=><button key={value} className={service===value?'pos-payment-choice selected':'pos-payment-choice'} onClick={()=>setService(value)} type="button">{serviceLabel[value]}</button>)}</div><p className="muted small">Choisissez uniquement le type commercial et les portions. Le menu détaillé du jour reste masqué.</p><Loading loading={catalog.isLoading} error={catalog.error}/>{commercialCategory===null?<div className="pos-home-actions">{productCategories.map(category=><button key={category.code} type="button" className="secondary" onClick={()=>setCommercialCategory(category.code)}>{category.label}</button>)}</div>:<><button type="button" className="secondary" onClick={()=>setCommercialCategory(null)}>← Types commerciaux</button><div className="products">{catalog.data?.products.filter(product=>product.category.code===commercialCategory).map(product=><button key={product.id} type="button" className="product-card" onClick={()=>chooseProduct(product)}><ProductImage value={product.imageUrl} name={product.name}/><strong>{product.name}</strong><small>{product.category.label}</small><span>{money(product.price.amount,product.price.currency)}</span>{product.optionGroups.length>0&&<small>Personnaliser</small>}</button>)}</div></>}
          {customizing&&<div className="card section" role="dialog" aria-modal="true"><h3>Personnaliser · {customizing.name}</h3>{customizing.optionGroups.map(group=><fieldset key={group.id}><legend>{group.name}{group.required?' · obligatoire':''}</legend>{group.options.map(option=><label key={option.id}><input type={group.maxSelections===1?'radio':'checkbox'} name={group.id} checked={selection[group.id]?.includes(option.id)??false} onChange={event=>setSelection(current=>{const selected=current[group.id]??[];return {...current,[group.id]:event.target.checked?(group.maxSelections===1?[option.id]:[...selected,option.id]):selected.filter(id=>id!==option.id)};})}/>{option.name}{Number(option.priceDelta)>0?` + ${money(option.priceDelta,option.currency)}`:''}</label>)}</fieldset>)}<button type="button" className="primary" onClick={addCustomized}>Ajouter au panier</button><button type="button" className="secondary" onClick={()=>setCustomizing(null)}>Annuler</button></div>}
          {cart.map(line=><div className="item" key={line.key}><span>{line.product.name} × {line.quantity}<br/><small>{Object.entries(line.selections).flatMap(([group,ids])=>ids.map(id=>line.product.optionGroups.find(value=>value.id===group)?.options.find(value=>value.id===id)?.name)).filter(Boolean).join(' · ')}</small></span><div className="actions"><button type="button" className="secondary" onClick={()=>setCart(lines=>lines.map(value=>value.key===line.key?{...value,quantity:value.quantity-1}:value).filter(value=>value.quantity>0))}>−</button><b>{line.quantity}</b><button type="button" className="secondary" onClick={()=>setCart(lines=>lines.map(value=>value.key===line.key?{...value,quantity:value.quantity+1}:value))}>+</button><button type="button" className="secondary" onClick={()=>setCart(lines=>lines.filter(value=>value.key!==line.key))}>Retirer</button></div></div>)}
          {cart.length>0&&<><p>Total indicatif · calcul final par le serveur : <strong>{money(totalIndicatif)}</strong></p><button type="button" className="primary full" disabled={action.busy||!session.data} onClick={()=>void action.run(createSale,subscriber?'Commande abonné calculée.':'Vente enregistrée.')} >Continuer</button></>}
        </section>}
        {order&&<section className="card"><h2>{order.sourceChannel==='WHATSAPP'?'Commande WhatsApp':'Commande'} · {order.number}</h2><p>{order.client?`${order.client.firstName} ${order.client.lastName}`:'Vente directe anonyme'} · {serviceLabel[order.serviceCode??'']??order.serviceCode}</p>{order.client&&order.coverageReason&&<p className={Number(order.coveredAmount)>0?'success':'preview'}>{order.coverageReason}</p>}{order.items?.map(line=><div className="item" key={line.id}><span>{line.productSnapshot.name??'Article'} × {line.quantity}{line.supplementsSnapshot?.map((extra,index)=><small key={index}> · {extra.name}</small>)}</span><strong>{money(line.lineTotal,order.currency)}</strong></div>)}<div className="section"><p>Total commercial <strong>{money(order.commercialTotal??order.totalAmount,order.currency)}</strong></p><p>Couvert abonnement <strong>{money(order.coveredAmount,order.currency)}</strong></p><p>Déjà payé <strong>{money(order.paidAmount??'0',order.currency)}</strong></p><p>À payer <strong>{money(due,order.currency)}</strong></p></div>
          {order.client&&order.sourceChannel==='WHATSAPP'&&Number(due)>0&&<><h3>Ajouter une portion ou un supplément</h3><div className="products">{catalog.data?.products.filter(product=>!['REPAS','PETIT_DEJEUNER'].includes(product.category.code)).map(product=><button key={product.id} type="button" className="product-card" onClick={()=>chooseProduct(product)}><strong>{product.name}</strong><small>{product.category.label}</small><span>{money(product.price.amount,product.price.currency)}</span></button>)}</div>{cart.length>0&&<button className="secondary" type="button" disabled={action.busy} onClick={()=>void action.run(addPickupExtras,'Extras ajoutés. Le solde a été recalculé.')}>Ajouter les extras · {money(totalIndicatif)}</button>}</>}
          {order.client&&Number(due)===0&&<button type="button" className="primary full" disabled={action.busy||!session.data} onClick={()=>void action.run(()=>handover(order),'Remise enregistrée.')}>REMETTRE LE REPAS</button>}
          {Number(due)>0&&<><h3>Encaisser</h3><div className="pos-payment-methods">{[['CASH','Espèces'],['MPESA','M-Pesa'],['ORANGE_MONEY','Orange Money'],['AIRTEL_MONEY','Airtel Money'],['CARD','Carte'],['TRANSFER','Virement']].map(([code,label])=><button type="button" key={code} className={method===code?'pos-payment-choice selected':'pos-payment-choice'} onClick={()=>setMethod(code)}>{label}</button>)}</div>{method!=='CASH'&&<label>Référence de paiement<input value={reference} maxLength={120} onChange={event=>setReference(event.target.value)}/></label>}<label>{method==='CASH'?'Montant reçu':'Montant à encaisser'}<input inputMode="decimal" value={received||due} onChange={event=>setReceived(event.target.value)}/></label><button type="button" className="primary full" disabled={action.busy||!session.data} onClick={()=>void action.run(submitPayment,method==='CASH'?'Paiement confirmé.':`Paiement ${method} enregistré en attente de confirmation.`)}>{order.client?'ENCAISSER ET SERVIR':'ENCAISSER'}</button>{payment?.status==='PENDING'&&<p className="preview">Paiement en attente de confirmation. Ne remettez pas le repas avant confirmation.</p>}{payment?.status==='CONFIRMED'&&<p className="success">Paiement confirmé · Monnaie à rendre : {money(payment.changeAmount,payment.changeCurrency??order.currency)}</p>}</>}
          {completed&&<button type="button" className="secondary" onClick={reset}>Retour à l’accueil POS</button>}
          {order.status==='SERVED'&&<button type="button" className="secondary" onClick={()=>void action.run(async()=>{const duplicate=await api<Order>(`/orders/${order.id}/receipt?duplicate=true`);setOrder(duplicate);window.setTimeout(()=>window.print(),100);},'Duplicata prêt à imprimer.')}>RÉIMPRIMER · DUPLICATA</button>}
        </section>}
      </>}
    </div>
    {order&&(completed||order.status==='SERVED'||payment?.status==='CONFIRMED')&&<section className="receipt print-only"><h1>JAMI FOOD</h1><strong>{order.receiptCopy??(order.client?'TICKET DE SERVICE':'REÇU DE VENTE')}</strong>{order.receiptCopy==='DUPLICATA'&&<h2>DUPLICATA</h2>}<p>{order.client?`${order.client.firstName} ${order.client.lastName}`:'Vente comptoir anonyme'}</p>{order.subscriptionName&&<small>{order.subscriptionName}</small>}<p>{serviceLabel[order.serviceCode??'']??'Vente POS'} · {order.number}</p><p>{new Intl.DateTimeFormat('fr-CD',{dateStyle:'medium',timeStyle:'short'}).format(new Date(order.handoverAt??order.createdAt??new Date()))}</p>{order.items?.map(line=><div key={line.id}><span>{line.productSnapshot.name??'Article'} × {line.quantity}</span><strong>{money(line.lineTotal,order.currency)}</strong></div>)}<hr/><p>Valeur commerciale : {money(order.commercialTotal??order.totalAmount,order.currency)}</p>{Number(order.coveredAmount)>0&&<p>Couvert abonnement : {money(order.coveredAmount,order.currency)}</p>}<p>Montant encaissé : {money(order.paidAmount??payment?.amountDue??'0',order.currency)}</p><p>Caissier : {user?.firstName} {user?.lastName}</p><p>Merci</p></section>}
  </>;
}
