'use client';

import { useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { api } from '../../../lib/api';

type RequestRow={id:string;type:string;createdAt:string;email:string;client:{id:string;firstName:string;lastName:string;ulcNumber:string|null;faculty:string|null;promotion:string|null;residency:string|null;phone:string|null;category:{label:string}}};
const labels:Record<string,string>={STUDENT_HOME:'Étudiant résident',STUDENT_EXTERNAL:'Étudiant externe',STAFF:'Personnel ULC'};
export default function ClientVerificationPage(){const cache=useQueryClient();const pending=useQuery({queryKey:['client-verification-pending'],queryFn:()=>api<RequestRow[]>('/catalog/client-accounts/pending')});const [working,setWorking]=useState('');const [error,setError]=useState('');async function decide(row:RequestRow,decision:'VERIFIED'|'REJECTED'){setWorking(row.id);setError('');const reason=decision==='VERIFIED'?'Identité et justificatifs ULC contrôlés.':'Demande rejetée après vérification.';try{await api(`/catalog/client-accounts/${row.id}/verification`,{decision,reason});await cache.invalidateQueries({queryKey:['client-verification-pending']});}catch(e){setError(e instanceof Error?e.message:'La décision n’a pas été enregistrée.');}finally{setWorking('');}}return <div className="page"><header className="page-header"><div><p className="eyebrow">GESTION DES CLIENTS</p><h1>Vérification ULC</h1><p>Examinez les demandes avant d’activer les avantages de catégorie.</p></div></header>{error&&<p role="alert" className="error">{error}</p>}{pending.isLoading?<p>Chargement des demandes…</p>:pending.isError?<p role="alert" className="error">Impossible de charger les demandes de vérification.</p>:pending.data?.length?<div className="verification-list">{pending.data.map(row=><article className="card verification-card" key={row.id}><div><span className="eyebrow">{labels[row.type]??row.type} · {row.client.category.label}</span><h2>{row.client.firstName} {row.client.lastName}</h2><p>{row.email} · {row.client.phone??'Téléphone non fourni'}</p><p>Identifiant ULC : {row.client.ulcNumber??'—'} · Résidence : {row.client.residency??'—'}</p>{row.client.faculty&&<p>{row.client.faculty} · {row.client.promotion}</p>}<small>Demande du {new Date(row.createdAt).toLocaleString('fr-FR')}</small></div><div className="verification-actions"><button className="primary" disabled={working===row.id} onClick={()=>decide(row,'VERIFIED')}>Valider</button><button className="danger" disabled={working===row.id} onClick={()=>decide(row,'REJECTED')}>Rejeter</button></div></article>)}</div>:<section className="card"><h2>Aucune demande en attente</h2><p>Les nouvelles inscriptions ULC apparaîtront ici.</p></section>}</div>}
