'use client';

import { FormEvent,useEffect,useState } from 'react';
import Link from 'next/link';
import { clientApi } from '../../lib/api';
import { PageIntro } from '../../ui';
type Profile={firstName:string;lastName:string;email:string;emailVerifiedAt:string|null;photoUrl:string|null;phone:string|null;category:string;verificationStatus:string;ulcNumber:string|null;faculty:string|null;promotion:string|null;residency:string|null};
export default function ProfilePage(){const [profile,setProfile]=useState<Profile|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const[photoFailed,setPhotoFailed]=useState(false);useEffect(()=>{clientApi<Profile>('client/me').then(setProfile).catch(e=>setError(e.message));},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;setBusy(true);setMessage('');setError('');const d=new FormData(e.currentTarget);try{const saved=await clientApi<Profile>('client/profile',{method:'PATCH',body:{firstName:d.get('firstName'),lastName:d.get('lastName'),phone:String(d.get('phone')??'').trim()||null}});setProfile(saved);setMessage('Profil enregistré.');}catch(cause){setError(cause instanceof Error?cause.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const file=new FormData(form).get('photo');if(!(file instanceof File)||!file.size)return;setBusy(true);setError('');setMessage('');const data=new FormData();data.append('photo',file);try{const result=await clientApi<{photoUrl:string}>('client/profile/photo',{method:'POST',body:data});setPhotoFailed(false);setProfile(current=>current?{...current,photoUrl:`${result.photoUrl}?v=${Date.now()}`}:current);setMessage('Photo de profil mise à jour.');form.reset();}catch(cause){setError(cause instanceof Error?cause.message:'Envoi de la photo impossible.');}finally{setBusy(false);}}
 return <main className="page-wrap"><PageIntro eyebrow="MON JAMI FOOD" title="Mon profil" description="Consultez vos informations personnelles et les deux vérifications associées à votre compte."/>{error&&!profile&&<p className="form-error">{error}</p>}{profile&&<><section className="profile-photo-panel">{profile.photoUrl&&!photoFailed?<img src={profile.photoUrl} alt="Photo de profil" width="96" height="96" onError={()=>setPhotoFailed(true)}/>:<span className="account-orb" aria-hidden="true">{profile.firstName.slice(0,1)}{profile.lastName.slice(0,1)}</span>}<form onSubmit={upload}><label>Photo de profil<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required/></label><small>JPG, PNG ou WEBP · 5 Mo maximum</small><button className="button button-dark" type="submit" disabled={busy}>{busy?'Envoi…':'Mettre à jour la photo'}</button></form></section><form className="profile-form" onSubmit={submit}><label>Prénom<input name="firstName" defaultValue={profile.firstName} required maxLength={80}/></label><label>Nom<input name="lastName" defaultValue={profile.lastName} required maxLength={80}/></label><label>E-mail<input value={profile.email} disabled readOnly/></label><div className="verification-status">Adresse e-mail : <b>{profile.emailVerifiedAt?'Vérifiée':'À vérifier'}</b>{!profile.emailVerifiedAt&&<Link href="/email-verification-pending">Vérifier mon e-mail</Link>}</div><label>Téléphone<input name="phone" type="tel" defaultValue={profile.phone??''} maxLength={30}/></label><label>Identifiant ULC<input value={profile.ulcNumber??''} disabled readOnly/></label><label>Catégorie<input value={profile.category} disabled readOnly/></label><div className="verification-status">Vérification d’identité ULC : <b>{profile.verificationStatus==='PENDING'?'En attente':profile.verificationStatus==='VERIFIED'?'Vérifiée':profile.verificationStatus==='REJECTED'?'Refusée':profile.verificationStatus}</b></div>{profile.faculty&&<p>Faculté : {profile.faculty} · Promotion : {profile.promotion}</p>}{error&&<p className="form-error">{error}</p>}{message&&<p className="form-note" role="status">{message}</p>}<button className="button button-dark" type="submit" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}</button></form></>}</main>}
