'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, Clock3, MapPin, Sparkles, Utensils } from './icons';

export default function HomePage() {
  const [splash, setSplash] = useState(true);
  useEffect(() => { if (sessionStorage.getItem('jami_splash_seen') === '1') { setSplash(false); return; } const timer = window.setTimeout(() => { sessionStorage.setItem('jami_splash_seen', '1'); setSplash(false); }, 1450); return () => window.clearTimeout(timer); }, []);
  if (splash) return <main className="splash" aria-label="JAMI FOOD"><div className="splash-orbit orbit-one"/><div className="splash-orbit orbit-two"/><div className="splash-center"><span className="splash-symbol">J<span>F</span></span><p className="splash-name">JAMI <b>FOOD</b></p><span className="splash-tagline">LE GOÛT DU CAMPUS</span><i className="splash-progress"/></div><span className="splash-bottom">UNIVERSITÉ LOYOLA DU CONGO · KINSHASA</span></main>;
  return <main>
    <section className="welcome-hero"><div className="welcome-copy"><span className="eyebrow eyebrow-light"><Sparkles size={14} /> LA PAUSE QUI RASSEMBLE</span><h1>Bienvenue<br/>chez <em>JAMI FOOD</em></h1><p>Les saveurs du campus, préparées avec soin et servies avec le sourire. Votre prochaine pause commence ici.</p><div className="hero-actions"><Link className="button button-gold" href="/menu">Découvrir le menu <ArrowRight size={17}/></Link><Link className="hero-quiet" href="/welcome">Comment ça marche <ArrowDown size={15}/></Link></div><div className="hero-meta"><span><MapPin size={15}/> Université Loyola du Congo</span><span><Clock3 size={15}/> À deux pas de vos cours</span></div></div><div className="hero-art" aria-label="Illustration de table au restaurant"><div className="hero-glow"/><div className="plate plate-back"><span>J</span></div><div className="plate plate-front"><div className="food-leaf leaf-a"/><div className="food-leaf leaf-b"/><div className="food-leaf leaf-c"/><div className="food-tomato"/><div className="food-grain"/><span className="plate-stamp">BON<br/>& FRAIS</span></div><div className="art-spark spark-a">✳</div><div className="art-spark spark-b">✦</div><div className="art-note">Fait avec<br/><b>le cœur.</b></div></div><div className="hero-bottom"><span>DU BON, DU FRAIS, DU CAMPUS.</span><span className="hero-index">01 <i/> 03</span></div></section>
    <section className="entry-section"><div className="entry-heading"><span className="eyebrow">VOTRE ESPACE, À VOTRE RYTHME</span><h2>Comment souhaitez-vous continuer ?</h2><p>Connectez-vous, rejoignez la communauté ULC ou explorez le menu en visiteur.</p></div><div className="entry-grid"><Link className="entry-card entry-login" href="/login"><span className="entry-icon">01</span><div><h3>Se connecter</h3><p>Retrouvez votre compte, vos commandes et votre espace personnel.</p></div><ArrowRight className="entry-arrow"/></Link><Link className="entry-card entry-register" href="/register"><span className="entry-icon">02</span><div><h3>Créer un compte</h3><p>Étudiants et personnel ULC : votre expérience JAMI FOOD commence ici.</p></div><ArrowRight className="entry-arrow"/></Link><Link className="entry-card entry-guest" href="/menu"><span className="entry-icon">03</span><div><h3>Continuer en visiteur</h3><p>Parcourez le menu et découvrez les saveurs du restaurant.</p></div><ArrowRight className="entry-arrow"/></Link></div><div className="entry-footnote"><span><Utensils size={15}/> Le menu est ouvert à tous.</span><span>La création de compte est réservée à la communauté ULC.</span></div></section>
    <section className="taste-strip"><span>UNE PAUSE</span><i/> <span>UN SOURIRE</span><i/> <span>UN GOÛT DE PLUS</span></section>
  </main>;
}
