'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {createContext,ReactNode,useContext,useEffect,useState} from 'react';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import {Menu,PanelLeftClose,LogOut,ChevronRight,ShieldAlert} from 'lucide-react';
import {api} from '../lib/api';
import {navigation,landingPage,roleLandingPage} from '../lib/navigation';
import {hasPageAccess as routeAllowed} from '../lib/route-access';
type User={username:string;firstName:string;lastName:string;roles:string[];permissions:string[]};
const UserContext=createContext<User|null>(null);
export const useUser=()=>useContext(UserContext);
function Frame({children}:{children:ReactNode}) {
  const path=usePathname(),router=useRouter();
  const [menuOpen,setMenuOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[network,setNetwork]=useState(true);
  const user=useQuery({queryKey:['me'],queryFn:()=>api<User>('/auth/me'),retry:false,enabled:path!=='/login'});
  const health=useQuery({queryKey:['api-ready'],queryFn:()=>api('/health/ready'),retry:false,refetchInterval:10000,networkMode:'always',enabled:path!=='/login'});
  useEffect(()=>{const update=()=>setNetwork(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
  useEffect(()=>{setMenuOpen(false);},[path]);
  useEffect(()=>{if(user.isError&&path!=='/login'&&health.isSuccess)router.replace('/login');},[user.isError,path,health.isSuccess,router]);
  useEffect(()=>{if(user.data?.roles.includes('CAISSIER')&&path!=='/pos'&&path!=='/login'){router.replace('/pos');return;}if(user.data&&path==='/'&&roleLandingPage(user.data.roles,user.data.permissions)){router.replace(roleLandingPage(user.data.roles,user.data.permissions)!);}else if(user.data&&path!=='/login'&&!routeAllowed(path,user.data.permissions)){const target=roleLandingPage(user.data.roles,user.data.permissions)??landingPage(user.data.permissions);if(target&&target!==path)router.replace(target);}},[path,user.data,router]);
  if(path==='/login')return <>{children}</>;
  if(!user.data)return <main><p role="status" className="loading">{user.isError?'Connexion impossible. Vérifiez le serveur puis réessayez.':'Chargement de votre espace…'}</p></main>;
  if(user.data.roles.includes('CAISSIER'))return <UserContext.Provider value={user.data}><main id="main-content" className="pos-only"><header className="topbar"><Link className="brand" href="/pos"><span>Jami</span><b>FOOD<span className="gold">●</span></b></Link><div className="top-actions"><strong>{user.data.firstName}</strong><button type="button" className="icon-button" aria-label="Se déconnecter" onClick={async()=>{await api('/auth/logout',{});router.replace('/login');}}><LogOut size={18}/></button></div></header>{health.isError&&<p role="alert" className="error">API indisponible. Les opérations doivent être validées par le serveur.</p>}{path==='/pos'?children:<p role="status">Redirection vers le POS…</p>}</main></UserContext.Provider>;
  const allowed=navigation.filter(item=>user.data.permissions.includes(item.permission));
  const sections=[...new Set(allowed.map(item=>item.section))];
  const current=navigation.find(item=>item.href===path);
  return <UserContext.Provider value={user.data}><a className="skip-link" href="#main-content">Aller au contenu</a><div className={`shell ${collapsed?'nav-collapsed':''} ${menuOpen?'nav-open':''}`}>
    {menuOpen&&<button type="button" className="nav-overlay" aria-label="Fermer le menu" onClick={()=>setMenuOpen(false)}/>}
    <aside className="sidebar" id="main-navigation"><Link href={landingPage(user.data.permissions)??'/login'} className="brand"><span>Jami</span><b>FOOD<span className="gold">●</span></b><small>RESTAURANT · ULC</small></Link><nav aria-label="Navigation principale">{sections.map(section=><section className="nav-group" key={section}><h2>{section}</h2>{allowed.filter(item=>item.section===section).map(item=><Link key={item.href} href={item.href} aria-current={path===item.href?'page':undefined} className={path===item.href?'active':''}><span>{item.label}</span>{path===item.href&&<ChevronRight size={14}/>}</Link>)}</section>)}</nav><div className="sidebar-bottom">Université Loyola du Congo<br/><small>Kinshasa · Heure locale</small><p className="developer-signature">Développé par <a href="https://www.linkedin.com/in/imani-k-844107274/" target="_blank" rel="noreferrer">Imani Kalumuna</a></p></div></aside>
    <div className="workspace"><header className="topbar"><div className="header-context"><button type="button" className="icon-button mobile-menu" aria-label="Ouvrir le menu" aria-expanded={menuOpen} aria-controls="main-navigation" onClick={()=>setMenuOpen(!menuOpen)}><Menu size={20}/></button><button type="button" className="icon-button desktop-menu" aria-label={collapsed?'Afficher la navigation':'Réduire la navigation'} onClick={()=>setCollapsed(!collapsed)}><PanelLeftClose size={19}/></button><span className="muted">{current?.section}</span><ChevronRight size={13}/><strong>{current?.label??'Accès'}</strong></div><div className="top-actions"><span className={health.isSuccess?'online':'offline'} role="status">{health.isSuccess?'● Serveur accessible':!network?'● Réseau indisponible':'● Serveur indisponible'}</span><div className="header-user"><strong>{user.data.firstName}</strong><small>{user.data.roles?.map(role=>role.replaceAll('_',' ')).join(' · ')}</small></div><button type="button" className="icon-button" aria-label="Se déconnecter" onClick={async()=>{await api('/auth/logout',{});router.replace('/login');}}><LogOut size={18}/></button></div></header>
    <main id="main-content"><div className="preview">Recette en cours · Les paramètres commerciaux non validés restent bloqués</div>{health.isError&&<p role="alert" className="error">L’API ou la base est inaccessible. Aucune opération n’est validée hors serveur. Vérifiez le LAN et l’alimentation ; une coupure Internet seule n’empêche pas un serveur local accessible de fonctionner.</p>}{routeAllowed(path,user.data.permissions)?children:<section className="card access-denied"><ShieldAlert size={32}/><h1>Accès refusé</h1><p>Votre compte ne dispose pas de la permission nécessaire. Aucune donnée de cette page n’a été chargée.</p><Link className="secondary" href={landingPage(user.data.permissions)??'/login'}>Retour à mon espace</Link></section>}</main><footer>JAMI FOOD · Gestion du restaurant ULC <span>Développé par <a href="https://www.linkedin.com/in/imani-k-844107274/" target="_blank" rel="noreferrer">Imani Kalumuna</a></span></footer></div></div></UserContext.Provider>;
}
export function Shell({children}:{children:ReactNode}){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{staleTime:10000,retry:1}}}));return <QueryClientProvider client={client}><Frame>{children}</Frame></QueryClientProvider>;}
