'use client';
import { useState } from 'react';
import { api, date, money } from '../../lib/api';
import { Feedback, Field, formValues, Heading, Loading, useAction, useData } from '../../components/common';
import { useUser } from '../../components/shell';
type Register={id:string;code:string;label:string;active:boolean};
type Cashier={id:string;firstName:string;lastName:string;username:string};
type ActiveSession={id:string;status:string;openedAt:string;openingUsd:string;openingCdf:string;cashier:Cashier;cashRegister:Register};
type Closing={id:string;cashSessionId:string;status:string;countedUsd:string;countedCdf:string;submittedAt:string;validatedAt:string|null;theoreticalSnapshot:{USD:string;CDF:string;digitalUSD:string;digitalCDF:string};varianceSnapshot:{USD:string;CDF:string;reason:string}};
export default function Cash(){
  const session=useData<{id:string;openedAt:string;status:string}|null>('/cash');
  const registers=useData<Register[]>('/cash/registers');
  const cashiers=useData<Cashier[]>('/cash/cashiers');
  const activeSessions=useData<ActiveSession[]>('/cash/active-sessions');
  const closings=useData<Closing[]>('/cash/closings');
  const action=useAction(),user=useUser();
  const [newRegister,setNewRegister]=useState(true);
  const [selected,setSelected]=useState<Closing|null>(null);
  const manager=user?.permissions.includes('cash.open')??false;
  return <>
    <Heading title="Caisses & clôtures" subtitle="Le Gestionnaire prépare la caisse et l’affecte au Caissier avant le service."/>
    <Feedback {...action}/>
    {manager&&<div className="two-columns">
      <section className="card"><h2>Préparer une session Caissier</h2><p className="muted">Le Caissier se connecte ensuite avec son propre compte. Il ne choisit ni n’ouvre une caisse.</p><form onSubmit={event=>{event.preventDefault();void action.run(()=>api('/cash/open',formValues(event.currentTarget),crypto.randomUUID()),'Caisse ouverte et affectée au Caissier.');}}><label>Caisse<select name="cashRegisterId" required defaultValue=""><option value="" disabled>Choisir une caisse active</option>{registers.data?.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.label} · {item.code}</option>)}</select></label><label>Caissier<select name="cashierId" required defaultValue=""><option value="" disabled>Choisir un Caissier actif</option>{cashiers.data?.map(item=><option key={item.id} value={item.id}>{item.firstName} {item.lastName} · {item.username}</option>)}</select></label><div className="form-grid"><Field name="openingUsd" label="Fonds initial · USD" type="number" defaultValue="0"/><Field name="openingCdf" label="Fonds initial · CDF" type="number" defaultValue="0"/></div><button className="primary" disabled={action.busy||!registers.data?.some(item=>item.active)||!cashiers.data?.length}>Affecter et ouvrir</button></form></section>
      <section className="card"><div className="toolbar"><h2>Caisses</h2><button className="secondary" type="button" onClick={()=>setNewRegister(value=>!value)}>{newRegister?'Gérer les caisses':'Créer une caisse'}</button></div>{newRegister&&<form onSubmit={event=>{event.preventDefault();void action.run(()=>api('/cash/registers',formValues(event.currentTarget),crypto.randomUUID()),'Caisse créée.');event.currentTarget.reset();}}><Field name="label" label="Nom de la caisse"/><Field name="code" label="Code unique"/><button className="primary" disabled={action.busy}>Créer</button></form>}<Loading loading={registers.isLoading} error={registers.error}/><div className="list">{registers.data?.map(item=><details className="item" key={item.id}><summary><strong>{item.label}</strong> · {item.code} · {item.active?'ACTIVE':'INACTIVE'}</summary><form onSubmit={event=>{event.preventDefault();const values=formValues(event.currentTarget);void action.run(()=>api(`/cash/registers/${item.id}/update`,{...values,active:values.active==='true'},crypto.randomUUID()),'Configuration de la caisse mise à jour.');}}><Field name="label" label="Nom" defaultValue={item.label}/><Field name="code" label="Code unique" defaultValue={item.code}/><label>État<select name="active" defaultValue={String(item.active)}><option value="true">ACTIVE</option><option value="false">INACTIVE</option></select></label><button className="secondary" type="submit" disabled={action.busy}>Enregistrer</button></form></details>)}</div></section>
    </div>}
    {manager&&<section className="card section"><h2>Sessions actives</h2><Loading loading={activeSessions.isLoading} error={activeSessions.error}/><div className="list">{activeSessions.data?.map(item=><div className="item" key={item.id}><span><strong>{item.cashier.firstName} {item.cashier.lastName}</strong><br/><small>{item.cashRegister.label} · {item.cashRegister.code} · {date(item.openedAt)}</small><details className="section"><summary>Clôturer cette caisse</summary><form onSubmit={event=>{event.preventDefault();void action.run(()=>api(`/cash/${item.id}/close`,formValues(event.currentTarget),crypto.randomUUID()),'Session clôturée.');}}><div className="form-grid"><Field name="countedUsd" label="Compté USD" type="number" defaultValue={item.openingUsd}/><Field name="countedCdf" label="Compté CDF" type="number" defaultValue={item.openingCdf}/></div><label>Motif / observations<textarea name="reason" maxLength={500}/></label><button className="primary" disabled={action.busy}>Clôturer</button></form></details></span><span className="badge">{item.status}</span></div>)}</div>{!activeSessions.data?.length&&<p className="empty">Aucune session ouverte.</p>}</section>}
    {session.data&&<section className="card section"><h2>Clôturer ma session</h2><p className="muted">Session ouverte le {date(session.data.openedAt)}. Saisissez le comptage physique.</p><form onSubmit={event=>{event.preventDefault();void action.run(()=>api(`/cash/${session.data!.id}/close`,formValues(event.currentTarget),crypto.randomUUID()),'Clôture soumise.');}}><div className="form-grid"><Field name="countedUsd" label="Espèces comptées · USD" type="number"/><Field name="countedCdf" label="Espèces comptées · CDF" type="number"/></div><label>Motif / observations<textarea name="reason" maxLength={500}/></label><button className="primary" disabled={action.busy}>Soumettre la clôture</button></form></section>}
    {!manager&&!session.data&&<p className="error">Aucune caisse active ne vous est affectée. Contactez le Gestionnaire.</p>}
    <section className="card section"><h2>Historique des clôtures</h2><Loading loading={closings.isLoading} error={closings.error}/><div className="table-wrap"><table><thead><tr><th>Date</th><th>Compté USD</th><th>Compté CDF</th><th>Écart</th><th>État</th><th>Actions</th></tr></thead><tbody>{closings.data?.map(item=><tr key={item.id}><td>{date(item.submittedAt)}</td><td>{money(item.countedUsd,'USD')}</td><td>{money(item.countedCdf,'CDF')}</td><td>{money(item.varianceSnapshot.USD,'USD')} / {money(item.varianceSnapshot.CDF)}</td><td>{item.status}</td><td><button className="secondary" type="button" onClick={()=>setSelected(item)}>Détails</button>{item.status!=='VALIDATED'&&user?.permissions.includes('cash.validate')&&<button className="primary" type="button" disabled={action.busy} onClick={()=>void action.run(()=>api(`/cash/closings/${item.id}/validate`,{},crypto.randomUUID()),'Clôture validée.')}>Valider</button>}{user?.permissions.includes('reports.export')&&<a className="secondary" href={`/api/v1/cash/closings/${item.id}/export`}>Exporter</a>}</td></tr>)}</tbody></table></div>{!closings.data?.length&&<p className="empty">Aucune clôture enregistrée.</p>}</section>
    {selected&&<section className="card section"><h2>Rapport de clôture · {date(selected.submittedAt)}</h2><p>Session {selected.cashSessionId} · {selected.status}</p><table><thead><tr><th>Devise</th><th>Théorique</th><th>Compté</th><th>Écart</th><th>Numérique</th></tr></thead><tbody>{(['USD','CDF'] as const).map(currency=><tr key={currency}><td>{currency}</td><td>{selected.theoreticalSnapshot[currency]}</td><td>{currency==='USD'?selected.countedUsd:selected.countedCdf}</td><td>{selected.varianceSnapshot[currency]}</td><td>{currency==='USD'?selected.theoreticalSnapshot.digitalUSD:selected.theoreticalSnapshot.digitalCDF}</td></tr>)}</tbody></table><p>Motif : {selected.varianceSnapshot.reason||'Aucun'}</p><div className="actions"><button className="primary" type="button" onClick={()=>window.print()}>Imprimer</button><button className="secondary" type="button" onClick={()=>setSelected(null)}>Fermer</button></div></section>}
  </>;
}
