const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const { randomUUID } = require('node:crypto');
const path = require('node:path');
require('reflect-metadata');
const root=path.resolve(__dirname,'../../..');
process.loadEnvFile(path.join(root,'.env'));
const testName='jami_test_'+Date.now();
const url=new URL(process.env.DATABASE_URL);url.pathname='/'+testName;
process.env.DATABASE_URL=url.toString();process.env.NODE_ENV='test';process.env.SEED_DEMO='true';process.env.WEB_ORIGIN='http://localhost:3000';
let app,db,base,cookie,caissierCookie,stockCookie,adminCookie,session,cashierSession,managerSession,products,order,client,sub,stockItem,purchase,closing,managerCookie;
const key=()=>randomUUID();
async function request(route,body,idem=key(),auth=cookie){const response=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',origin:'http://localhost:3000','x-jami-request':'1','idempotency-key':idem,...(auth?{cookie:auth}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await response.json();return{status:response.status,...result,cookie:response.headers.get('set-cookie')?.split(';')[0]};}
async function ok(route,body,idem,auth){const r=await request(route,body,idem,auth);assert.ok(r.success,JSON.stringify(r));return r.data;}
before(async()=>{
 execFileSync('docker',['exec','jami-food-dev-db','createdb','-U','jami',testName]);
 execFileSync(process.execPath,[path.join(root,'packages/database/node_modules/prisma/build/index.js'),'migrate','deploy','--schema',path.join(root,'packages/database/prisma/schema.prisma')],{cwd:root,env:process.env,stdio:'pipe'});
 execFileSync(process.execPath,['--import',path.join(root,'packages/database/node_modules/tsx/dist/loader.mjs'),path.join(root,'packages/database/prisma/seed.ts')],{cwd:root,env:process.env,stdio:'pipe'});
 const {NestFactory}=require('@nestjs/core'); const {AppModule}=require('../dist/app.module'); const {PrismaService}=require('../dist/prisma.service');
 app=await NestFactory.create(AppModule,{logger:false});app.setGlobalPrefix('api/v1');await app.listen(0,'127.0.0.1');base=(await app.getUrl())+'/api/v1';db=app.get(PrismaService);
 cookie=(await request('/auth/login',{username:'responsable.demo',password:process.env.DEMO_PASSWORD},key(),null)).cookie;assert.ok(cookie);
 caissierCookie=(await request('/auth/login',{username:'caissier.demo',password:process.env.DEMO_PASSWORD},key(),null)).cookie;
 managerCookie=(await request('/auth/login',{username:'gestionnaire.demo',password:process.env.DEMO_PASSWORD},key(),null)).cookie;
 adminCookie=(await request('/auth/login',{username:'admintech.demo',password:process.env.DEMO_PASSWORD},key(),null)).cookie;
 stockCookie=adminCookie;
}, {timeout:60000});
after(async()=>{if(app)await app.close();execFileSync('docker',['exec','jami-food-dev-db','dropdb','-U','jami','--if-exists',testName]);});
test('Authentification obligatoire, CSRF et origine étrangère',async()=>{assert.equal((await request('/clients',undefined,key(),null)).status,401);const r=await fetch(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'responsable.demo',password:process.env.DEMO_PASSWORD})});assert.equal(r.status,403);const foreign=await fetch(base+'/auth/logout',{method:'POST',headers:{cookie,origin:'https://foreign.example','x-jami-request':'1','content-type':'application/json'},body:'{}'});assert.equal(foreign.status,403);});
test('R11 caissier refusé pour taux, validation et exports',async()=>{assert.equal((await request('/exchange-rates',{rate:'2600',source:'test',effectiveFrom:new Date().toISOString()},key(),caissierCookie)).status,403);assert.equal((await request('/cash/closings/'+randomUUID()+'/validate',{},key(),caissierCookie)).status,403);});
test('RBAC refusé avant lecture objet et opérations financières',async()=>{
 const cases=[
  ['/orders/'+randomUUID()+'/cancel',{},caissierCookie],
  ['/subscriptions/'+randomUUID(),undefined,caissierCookie],
  ['/clients/'+randomUUID(),undefined,caissierCookie],
  ['/reports',undefined,caissierCookie],
  ['/stock/purchases/'+randomUUID()+'/payments',{cashSessionId:randomUUID(),amount:'1'},stockCookie],
  ['/orders/payments/'+randomUUID()+'/refund',{cashSessionId:randomUUID(),amount:'1',reason:'test'},adminCookie],
 ];
 for(const [route,body,auth] of cases){const result=await request(route,body,key(),auth);assert.equal(result.status,403,route);assert.equal(Object.hasOwn(result,'data'),false,route);}
});
test('Ouverture de caisse et catalogue tarifé côté serveur',async()=>{const registers=await ok('/cash/registers');session=await ok('/cash/open',{cashRegisterId:registers[0].id,openingUsd:'0',openingCdf:'10000'});products=await ok('/products');assert.equal(products.length,2);});
test('R07 vente 9700 CDF, reçu 5 USD, rendu 2800 CDF et idempotence',async()=>{const body={categoryCode:'ETUDIANT_EXTERNE',serviceMode:'DINE_IN',currency:'CDF',items:products.map(p=>({productId:p.id,quantity:1}))};const k=key();const [a,b]=await Promise.all([ok('/orders',body,k),ok('/orders',body,k)]);assert.equal(a.id,b.id);order=a;assert.equal(order.totalAmount,'9700');const pk=key(),pay={cashSessionId:session.id,method:'CASH',receivedAmount:'5',receivedCurrency:'USD'};const p=await ok('/orders/'+order.id+'/payments',pay,pk);assert.equal(p.changeAmount,'2800');assert.equal((await ok('/orders/'+order.id+'/payments',pay,pk)).id,p.id);assert.equal(await db.cashMovement.count({where:{paymentId:p.id}}),2);assert.equal((await request('/orders/'+order.id+'/payments',pay)).status,409);assert.equal((await request('/orders', {...body,items:[body.items[0]]},k)).status,409);});
test('Vente POS payée prête et reçu disponible sans file de préparation',async()=>{assert.equal(order.status,'READY');assert.equal((await ok('/orders/'+order.id+'/receipt')).number,order.number);assert.equal((await request('/kitchen')).status,404);assert.equal((await request('/delivery')).status,404);});
test('R08 paiement externe en attente puis confirmation répétée',async()=>{const o=await ok('/orders',{categoryCode:'ETUDIANT_EXTERNE',serviceMode:'TAKEAWAY',currency:'CDF',items:[{productId:products[0].id,quantity:1}]});const p=await ok('/orders/'+o.id+'/payments',{cashSessionId:session.id,method:'MPESA',receivedAmount:o.totalAmount,receivedCurrency:'CDF',externalReference:'TEST-'+key()});assert.equal(p.status,'PENDING');assert.equal(await db.cashMovement.count({where:{paymentId:p.id}}),0);await Promise.all([ok('/orders/payments/'+p.id+'/confirm',{}),ok('/orders/payments/'+p.id+'/confirm',{})]);assert.equal(await db.cashMovement.count({where:{paymentId:p.id}}),1);});
test('R09 nouveau tarif sans réécriture de l’ancienne vente',async()=>{const before=await db.order.findUniqueOrThrow({where:{id:order.id}});const product=products[0];await ok('/pricing/'+product.prices[0].id,{amount:'9000',currency:'CDF'});const n=await ok('/orders',{categoryCode:'ETUDIANT_EXTERNE',serviceMode:'DINE_IN',currency:'CDF',items:[{productId:product.id,quantity:1}]});assert.equal(n.totalAmount,'9000');assert.equal((await db.order.findUniqueOrThrow({where:{id:order.id}})).totalAmount.toString(),before.totalAmount.toString());});
test('R01 souscription datée D+29, paiement et code opaque',async()=>{const cat=(await ok('/clients/categories'))[0];client=await ok('/clients',{firstName:'Recette',lastName:key(),categoryId:cat.id},undefined,managerCookie);const plan=(await ok('/subscriptions/plans',undefined,undefined,managerCookie)).find(p=>p.name==='Repas');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kinshasa'}).format(new Date());sub=await ok('/subscriptions',{clientId:client.id,planVersionId:plan.versions[0].id,startsOn:today},undefined,managerCookie);assert.equal((new Date(sub.endsOn)-new Date(sub.startsOn))/86400000,29);const register=await db.cashRegister.create({data:{code:'MANAGER-'+key(),label:'Caisse gestionnaire'}});managerSession=await ok('/cash/open',{cashRegisterId:register.id,openingUsd:'0',openingCdf:'0'},undefined,managerCookie);await ok('/subscriptions/'+sub.id+'/payments',{cashSessionId:managerSession.id,method:'CASH',receivedAmount:sub.amount,receivedCurrency:'USD'},undefined,managerCookie);assert.equal(await db.mealConsumption.count(),0);});
test('WhatsApp abonné: READY, droit réservé, recherche POS, retrait idempotent et reçu',async()=>{const cashierRegisters=await ok('/cash/registers',undefined,undefined,caissierCookie);cashierSession=await ok('/cash/open',{cashRegisterId:cashierRegisters[1].id,openingUsd:'0',openingCdf:'0'},undefined,caissierCookie);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kinshasa'}).format(new Date());const menu=await ok('/menus',{businessDate:today,serviceCode:'LUNCH'},undefined,managerCookie);for(const p of products)await ok('/menus/versions/'+menu.id+'/items',{productId:p.id,quantityAvailable:10},undefined,managerCookie);await ok('/menus/versions/'+menu.id+'/publish',{},undefined,managerCookie);const body={subscriberId:client.id,businessDate:today,serviceCode:'LUNCH',menuVersionId:menu.id,items:[{productId:products[0].id,quantity:1}]};const idempotency=key();const [a,b]=await Promise.all([ok('/orders/whatsapp',body,idempotency,managerCookie),ok('/orders/whatsapp',body,idempotency,managerCookie)]);assert.equal(a.id,b.id);assert.equal(a.status,'READY');const reservation=await db.mealReservation.findUniqueOrThrow({where:{orderId:a.id},include:{mealRight:true}});assert.equal(reservation.mealRight.status,'RESERVED');const found=await ok('/orders/ready-for-pickup?q='+encodeURIComponent(client.lastName),undefined,undefined,caissierCookie);assert.ok(found.orders.some(x=>x.id===a.id));const handoverKey=key();const [picked,again]=await Promise.all([ok('/orders/'+a.id+'/handover',{cashSessionId:cashierSession.id},handoverKey,caissierCookie),ok('/orders/'+a.id+'/handover',{cashSessionId:cashierSession.id},handoverKey,caissierCookie)]);assert.equal(picked.data.status,'SERVED');assert.equal(again.data.status,'SERVED');assert.equal((await db.mealRight.findUniqueOrThrow({where:{id:reservation.mealRightId}})).status,'CONSUMED');assert.equal((await ok('/orders/'+a.id+'/receipt',undefined,undefined,caissierCookie)).number,a.number);assert.equal((await request('/orders/'+a.id+'/handover',{cashSessionId:cashierSession.id},key(),caissierCookie)).status,409);});
test('Stock initial, pertes, stock négatif interdit, répétition sans double mouvement',async()=>{stockItem=await ok('/stock',{code:'TEST-'+key(),name:'Riz recette',unit:'kg',alertThreshold:'5'});await ok('/stock/'+stockItem.id+'/movements',{quantity:'10',type:'INITIAL',reason:'Stock de départ'});const k=key(),loss={quantity:'2',type:'LOSS',reason:'Perte constatée'};await Promise.all([ok('/stock/'+stockItem.id+'/movements',loss,k),ok('/stock/'+stockItem.id+'/movements',loss,k)]);assert.equal((await db.stockItem.findUniqueOrThrow({where:{id:stockItem.id}})).quantity.toString(),'8');assert.equal((await request('/stock/'+stockItem.id+'/movements',{...loss,quantity:'20'})).error.code,'INSUFFICIENT_STOCK');});
test('R15 réception répétée unique et règlement fournisseur sans entrée stock',async()=>{const supplier=await ok('/stock/suppliers',{name:'Fournisseur test'});purchase=await ok('/stock/purchases',{supplierId:supplier.id,amount:'1000',currency:'CDF'});const body={purchaseId:purchase.id,reference:'BL-'+key(),lines:[{stockItemId:stockItem.id,quantity:'4',unit:'kg'}]},k=key();await ok('/stock/receipts',body,k);await ok('/stock/receipts',body,k);const before=(await db.stockItem.findUniqueOrThrow({where:{id:stockItem.id}})).quantity.toString();await ok('/stock/purchases/'+purchase.id+'/payments',{cashSessionId:session.id,amount:'1000'});assert.equal((await db.stockItem.findUniqueOrThrow({where:{id:stockItem.id}})).quantity.toString(),before);});
test('Production déduit une seule fois les ingrédients',async()=>{const recipe=await ok('/stock/recipes',{name:'Riz test',yieldQuantity:'10',ingredients:[{stockItemId:stockItem.id,quantity:'1'}]});const version=recipe.versions[0];await ok('/stock/recipes/'+version.id+'/validate',{});const body={recipeVersionId:version.id,quantity:'20'},k=key();await ok('/stock/productions',body,k);await ok('/stock/productions',body,k);assert.equal((await db.stockItem.findUniqueOrThrow({where:{id:stockItem.id}})).quantity.toString(),'10');});
test('R16 inventaire justifié et validé une seule fois',async()=>{const inv=await ok('/stock/inventories',{stockItemId:stockItem.id,counted:'9',reason:'Écart physique vérifié'});await ok('/stock/inventories/'+inv.id+'/validate',{});assert.equal((await request('/stock/inventories/'+inv.id+'/validate',{})).status,409);assert.equal((await db.stockItem.findUniqueOrThrow({where:{id:stockItem.id}})).quantity.toString(),'9');});
test('R10 clôture aveugle, contrôle, export et immutabilité SQL',async()=>{const current=await ok('/cash');assert.equal(current.openingCdf,undefined);assert.equal(current.movements,undefined);const s=await db.cashSession.findUniqueOrThrow({where:{id:session.id},include:{movements:true}});let usd=Number(s.openingUsd),cdf=Number(s.openingCdf);for(const m of s.movements){if(!['CASH_IN','CASH_OUT'].includes(m.type))continue;const v=Number(m.amount)*(m.type==='CASH_IN'?1:-1);if(m.currency==='USD')usd+=v;else cdf+=v;}closing=await ok('/cash/'+session.id+'/close',{countedUsd:String(usd),countedCdf:String(cdf),reason:''});assert.equal(closing.varianceSnapshot.USD,'0');assert.equal(closing.varianceSnapshot.CDF,'0');await ok('/cash/closings/'+closing.id+'/validate',{});const exportResponse=await fetch(base+'/cash/closings/'+closing.id+'/export',{headers:{cookie}});assert.equal(exportResponse.status,200);assert.match(await exportResponse.text(),/Rapport de clôture/);await assert.rejects(db.cashClosing.update({where:{id:closing.id},data:{countedCdf:1}}));await assert.rejects(db.auditLog.deleteMany());});
