'use client';

import { useParams } from 'next/navigation';
import { useEffect,useState } from 'react';
import { clientApi } from '../../lib/api';
import { PageIntro,EmptyCard } from '../../ui';

type Order={id:string;number:string;status:string;serviceMode:string;totalAmount:string;commercialTotal:string;coveredAmount:string;mealRightId?:string|null;currency:string;createdAt:string;items:Array<{quantity:string;unitPrice:string;lineTotal:string;productSnapshot:unknown}>;statusHistory:Array<{toStatus:string;createdAt:string}>;delivery:{status:string;assignedAt:string|null;deliveredAt:string|null}|null};
const money=(value:string|number,currency:string)=>`${Number(value).toLocaleString('fr-FR')} ${currency}`;
export default function OrderDetailPage(){const {id}=useParams<{id:string}>();const [order,setOrder]=useState<Order|null>(null);const [error,setError]=useState('');useEffect(()=>{clientApi<Order>(`client/orders/${encodeURIComponent(id)}`).then(setOrder).catch(e=>setError(e.message));},[id]);return <main className="page-wrap"><PageIntro eyebrow="MES COMMANDES" title={order?order.number:'Détail de commande'} description="Suivi de commande depuis votre compte JAMI FOOD."/>{error?<EmptyCard title="Commande indisponible" text={error}/>:order?<section className="data-list"><article className="data-row"><b>Statut</b><strong>{order.status}</strong></article><article className="data-row"><b>Service</b><span>{order.serviceMode}</span></article>{order.items.map((item,i)=>{const snapshot=item.productSnapshot as {name?:string;coveredAmount?:number};return <div key={i}><article className="data-row"><b>{snapshot.name??'Article'}</b><span>{item.quantity} × {money(item.unitPrice,order.currency)}</span><strong>{money(item.lineTotal,order.currency)}</strong></article>{Number(snapshot.coveredAmount)>0&&<article className="data-row"><span>Couvert par abonnement</span><strong>−{money(snapshot.coveredAmount??0,order.currency)}</strong></article>}</div>})}{Number(order.coveredAmount)>0&&<article className="data-row"><b>Total commercial</b><strong>{money(order.commercialTotal,order.currency)}</strong></article>}<article className="data-row"><b>À payer</b><strong>{money(order.totalAmount,order.currency)}</strong></article>{order.statusHistory.map((step,i)=><article className="data-row" key={i}><b>{step.toStatus}</b><small>{new Date(step.createdAt).toLocaleString('fr-FR')}</small></article>)}</section>:<p role="status">Chargement de la commande…</p>}</main>}
