'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { ArrowLeft, GraduationCap, UserRound } from '../icons';
import { clientApi } from '../lib/api';

type Kind = 'STUDENT_HOME'|'STUDENT_EXTERNAL'|'STAFF';
export default function RegisterPage() {
  const router = useRouter(); const [kind,setKind]=useState<Kind|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(!kind)return;setError('');setBusy(true);const data=new FormData(event.currentTarget);const value=(key:string)=>String(data.get(key)??'').trim();try{await clientApi('client/register',{method:'POST',body:{type:kind,firstName:value('firstName'),lastName:value('lastName'),email:value('email'),password:value('password'),confirmPassword:value('confirmPassword'),ulcNumber:value('ulcNumber'),faculty:value('faculty'),promotion:value('promotion'),phone:value('phone')||undefined}});router.push('/account');router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Inscription impossible.');}finally{setBusy(false);}}
  return <main className="auth-layout register-layout"><Link href="/" className="back-link"><ArrowLeft size={16}/> Retour à l’accueil</Link><section className="auth-card register-card"><span className="eyebrow">REJOIGNEZ LA COMMUNAUTÉ</span><h1>Votre compte JAMI FOOD.</h1><p>La création de compte est réservée aux étudiants et au personnel de l’ULC.</p><div className="choice-grid"><button type="button" className={kind==='STUDENT_HOME'||kind==='STUDENT_EXTERNAL'?'choice-card selected':'choice-card'} onClick={()=>setKind(kind?.startsWith('STUDENT')?kind:'STUDENT_HOME')}><GraduationCap/><span><b>Étudiant ULC</b><small>Résident au Home ou externe</small></span></button><button type="button" className={kind==='STAFF'?'choice-card selected':'choice-card'} onClick={()=>setKind('STAFF')}><UserRound/><span><b>Personnel ULC</b><small>Enseignant ou membre du personnel</small></span></button></div>{kind&&<form className="auth-form register-form" onSubmit={submit}>{kind!=='STAFF'&&<div className="residency-choice"><span className="eyebrow">VOTRE RÉSIDENCE</span><div><button type="button" className={kind==='STUDENT_HOME'?'chip selected':'chip'} onClick={()=>setKind('STUDENT_HOME')}>Résident au Home</button><button type="button" className={kind==='STUDENT_EXTERNAL'?'chip selected':'chip'} onClick={()=>setKind('STUDENT_EXTERNAL')}>Étudiant externe</button></div></div>}<label>Prénom<input name="firstName" autoComplete="given-name" required maxLength={80}/></label><label>Nom<input name="lastName" autoComplete="family-name" required maxLength={80}/></label><label>E-mail<input name="email" type="email" autoComplete="email" placeholder="nom@ulc.cd" required maxLength={254}/></label><label>Identifiant ULC / matricule<input name="ulcNumber" required maxLength={50}/></label>{kind!=='STAFF'&&<><label>Faculté<input name="faculty" required maxLength={120}/></label><label>Promotion<input name="promotion" required maxLength={80}/></label></>}<label>Téléphone<input name="phone" type="tel" autoComplete="tel" maxLength={30}/></label><label>Mot de passe<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={256} required/></label><label>Confirmer le mot de passe<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={256} required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<p className="form-note">Votre compte sera créé en attente de vérification ULC. Vos avantages tarifaires restent inactifs jusqu’à validation.</p><button className="button button-dark full" type="submit" disabled={busy}>{busy?'Création…':'Créer mon compte'}</button></form>}<div className="auth-links"><span>Vous avez déjà un compte ? <Link href="/login">Se connecter</Link></span></div></section></main>;
}
