'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { clientApi } from '../lib/api';
import { subscriptionStatus } from '../lib/subscription-status';
import { ArrowRight } from '../icons';
import { EmptyCard, PageIntro } from '../ui';

type Row=Record<string,unknown>;
const titles:Record<string,string>={subscriptions:'Mon abonnement',rights:'Mes droits',orders:'Mes commandes',payments:'Mes paiements',receipts:'Mes reçus',deliveries:'Mes livraisons',activity:'Mon historique'};
function display(value:unknown):string { if(value instanceof Date)return value.toLocaleDateString('fr-FR',{timeZone:'Africa/Kinshasa'});if(typeof value==='string'&&/^\d{4}-\d\d-\d\d$/.test(value)){const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('fr-FR');}if(typeof value==='string'&&/^\d{4}-\d\d-\d\dT/.test(value))return new Date(value).toLocaleDateString('fr-FR',{timeZone:'Africa/Kinshasa'});if(typeof value==='object'&&value!==null&&'name'in value)return String((value as {name:unknown}).name);if(typeof value==='object'&&value!==null&&'plan'in value)return display((value as {plan:unknown}).plan);return String(value??'—'); }
function subscriptionDetails(row:Row){const version=row.planVersion&&typeof row.planVersion==='object'?row.planVersion as Record<string,unknown>:{};const services=version.services??row.serviceSnapshot;const serviceLabels=Array.isArray(services)?services.map(display).join(', '):services&&typeof services==='object'?Object.keys(services).join(', '):'Services selon la formule';const rights=Array.isArray(row.rights)?row.rights as Row[]:[];const consumed=rights.filter(right=>right.status==='CONSUMED').length;const available=rights.filter(right=>right.status==='AVAILABLE').length;const reserved=rights.filter(right=>right.status==='RESERVED').length;return `Services : ${serviceLabels} · droits : ${available} disponibles, ${reserved} réservés, ${consumed} consommés · ${row.deliveryIncluded?'livraison incluse':'livraison non incluse'}`;}
 export function AccountDataView({section}:{section:string}){
 const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const endpoint=section==='subscriptions'?'subscriptions':section;
 useEffect(()=>{clientApi<Row[]>(`client/${endpoint}`).then(setRows).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[endpoint]);
 return <main className="page-wrap"><PageIntro eyebrow="MON JAMI FOOD" title={titles[section]??section} description="Informations récupérées depuis votre compte JAMI FOOD."/>{section==='subscriptions'&&<p className="form-note">Chaque droit couvre un repas correspondant au service prévu. Les suppléments sont facturés séparément.</p>}{loading?<p role="status">Chargement…</p>:error?<EmptyCard title="Connexion nécessaire" text={error} action={<Link className="button button-dark" href="/login">Se connecter</Link>}/>:rows.length===0?<EmptyCard title="Aucune donnée pour le moment" text="Les informations apparaîtront ici dès qu’elles seront disponibles sur votre compte." action={<Link className="text-link" href="/account">Retour à Mon JAMI FOOD <ArrowRight size={16}/></Link>}/>:<section className="data-list">{rows.map((row,index)=>{const orderId=typeof row.id==='string'&&section==='orders'?row.id:null;const primary=String(row.number??(section==='subscriptions'?display(row.planVersion):row.action??row.serviceCode??row.status)??'Activité');const date=section==='subscriptions'?display(row.startsOn)+' – '+display(row.endsOn):display(row.createdAt??row.businessDate??row.startsOn);const state=section==='subscriptions'?subscriptionStatus(row):null;return <article className="data-row" key={String(row.id??`${primary}-${index}`)}><div><b>{primary}</b>{state&&<span className={`subscription-status subscription-status-${state.kind}`}>{state.label}</span>}<small>{date}{section==='subscriptions'?` · ${subscriptionDetails(row)}`:` · ${String(row.status??row.action??'')}`}</small>{section==='subscriptions'&&<small>Paiement : {display(row.paidAmount)} {display(row.currency)} réglés · {display(row.balance)} {display(row.currency)} restants</small>}</div>{row.amount!==undefined&&<strong>{display(row.amount)} {display(row.currency)}</strong>}{row.totalAmount!==undefined&&<strong>{display(row.totalAmount)} {display(row.currency)}{Number(row.coveredAmount)>0?` · ${display(row.coveredAmount)} couverts`:''}</strong>}{orderId&&<Link className="text-link" href={`/orders/${orderId}`}>Détails <ArrowRight size={15}/></Link>}</article>})}</section>}</main>;
}
