'use client';

import Link from 'next/link';
import { FormEvent,useEffect,useState } from 'react';
import { ArrowRight,BookOpenCheck,CreditCard,History,PackageCheck,QrCode,ReceiptText,UserRound } from '../icons';
import { clientApi } from '../lib/api';
import { subscriptionStatus } from '../lib/subscription-status';
import { PageIntro } from '../ui';

type Profile={firstName:string;verificationStatus:string;photoUrl:string|null};
type Subscription={id:string;status:string;endsOn:string;startsOn:string;amount:string|number;paidAmount:string|number;balance:string|number;currency:string;planVersion:{plan:{name:string}}};
const areas=[{href:'/account/subscription',title:'Mon abonnement',text:'Formule, période et renouvellement',icon:BookOpenCheck},{href:'/account/rights',title:'Mes droits',text:'Vos droits repas et leur statut',icon:PackageCheck},{href:'/account/qr',title:'Mon QR Code',text:'Votre identifiant JAMI FOOD',icon:QrCode},{href:'/orders',title:'Mes commandes',text:'Suivre vos commandes',icon:PackageCheck},{href:'/account/payments',title:'Mes paiements',text:'Paiements liés à votre activité',icon:CreditCard},{href:'/account/receipts',title:'Mes reçus',text:'Retrouver vos justificatifs',icon:ReceiptText},{href:'/account/deliveries',title:'Mes livraisons',text:'Suivi de vos livraisons',icon:PackageCheck},{href:'/account/activity',title:'Mon historique',text:'Les moments de votre parcours',icon:History},{href:'/account/profile',title:'Mon profil',text:'Vos informations personnelles',icon:UserRound}];
function date(value:string){const [y,m,d]=value.slice(0,10).split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('fr-FR');}
export default function AccountPage(){
 const [profile,setProfile]=useState<Profile|null>(null);const [subscriptions,setSubscriptions]=useState<Subscription[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(true);const [logoutBusy,setLogoutBusy]=useState(false);const[photoFailed,setPhotoFailed]=useState(false);const[deleteOpen,setDeleteOpen]=useState(false);const[deletePassword,setDeletePassword]=useState('');const[deleteError,setDeleteError]=useState('');const[deleteBusy,setDeleteBusy]=useState(false);
 useEffect(()=>{clientApi<Profile>('client/me').then(setProfile).catch(e=>setError(e.message)).finally(()=>setBusy(false));clientApi<Subscription[]>('client/subscriptions').then(setSubscriptions).catch(()=>{});},[]);
 async function logout(){setLogoutBusy(true);setError('');try{await clientApi('client/logout',{method:'POST'});setProfile(null);window.location.assign('/login');}catch(cause){setError(cause instanceof Error?cause.message:'La déconnexion a échoué. Réessayez.');setLogoutBusy(false);}}
 async function deleteAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!window.confirm('Supprimer votre compte JAMI FOOD ? Votre fiche sera archivée et retirée des listes actives. Vos commandes et paiements historiques resteront conservés. Vos sessions et QR seront révoqués.'))return;setDeleteBusy(true);setDeleteError('');try{await clientApi('client/account',{method:'DELETE',body:{currentPassword:deletePassword}});setProfile(null);window.location.assign('/home');}catch(cause){setDeleteError(cause instanceof Error?cause.message:'La suppression du compte a échoué. Réessayez.');setDeleteBusy(false);}}
 const sub=subscriptions.find(value=>['ACTIVE','PENDING_PAYMENT','SCHEDULED'].includes(value.status))??subscriptions[0];const state=sub?subscriptionStatus(sub):null;
 return <main className="page-wrap account-home"><PageIntro eyebrow="VOTRE ESPACE PERSONNEL" title="Mon JAMI FOOD" description="Tout votre parcours JAMI FOOD, rassemblé au même endroit."/><section className="account-welcome">{profile?.photoUrl&&!photoFailed?<img className="account-orb" style={{objectFit:'cover'}} src={profile.photoUrl} alt="Photo de profil" onError={()=>setPhotoFailed(true)}/>:<span className="account-orb">J</span>}<div><span className="eyebrow eyebrow-light">BIENVENUE DANS VOTRE ESPACE</span><h2>{profile?`Bonjour ${profile.firstName} 👋`:'Votre compte JAMI FOOD'}</h2><p>{busy?'Chargement de votre compte…':error?error:profile?.verificationStatus==='PENDING'?'Votre compte attend la vérification ULC.':profile?.verificationStatus==='REJECTED'?'Votre demande a été rejetée. Contactez le service client.':'Retrouvez ici vos informations personnelles et votre parcours.'}</p></div>{profile?<button type="button" className="button button-gold" disabled={logoutBusy} onClick={logout}>{logoutBusy?'Déconnexion…':'Se déconnecter'}</button>:<Link href="/login" className="button button-gold">Se connecter <ArrowRight size={16}/></Link>}</section>
 {profile&&sub&&state&&<Link className="account-subscription-summary" href="/account/subscription"><div><small>MON ABONNEMENT</small><b>{sub.planVersion.plan.name}</b><span className={`subscription-status subscription-status-${state.kind}`}>{state.label}</span></div><div><small>ÉCHÉANCE</small><b>{date(sub.endsOn)}</b><small>Paiement : {Number(sub.paidAmount).toLocaleString('fr-FR')} {sub.currency} réglés · {Number(sub.balance).toLocaleString('fr-FR')} {sub.currency} restants</small></div><ArrowRight size={18}/></Link>}
  {profile&&<section className="account-grid" aria-label="Rubriques Mon JAMI FOOD">{areas.map(({href,title,text,icon:Icon})=><Link href={href} className="account-card" key={href}><span className="account-card-icon"><Icon size={20}/></span><span><b>{title}</b><small>{text}</small></span><ArrowRight className="account-card-arrow" size={17}/></Link>)}</section>}
  {profile&&<section className="account-delete-panel"><h2>Supprimer mon compte</h2><p>Votre fiche sera archivée et retirée des listes actives. Vos QR et sessions seront révoqués ; vos commandes et paiements historiques resteront conservés par le restaurant.</p>{!deleteOpen?<button type="button" className="button account-delete-button" onClick={()=>{setDeleteOpen(true);setDeleteError('');}}>Supprimer mon compte</button>:<form className="auth-form" onSubmit={deleteAccount}><label>Confirmez avec votre mot de passe actuel<input type="password" autoComplete="current-password" value={deletePassword} onChange={event=>setDeletePassword(event.target.value)} required maxLength={256}/></label>{deleteError&&<p className="form-error" role="alert">{deleteError}</p>}<div className="actions"><button type="submit" className="button account-delete-button" disabled={deleteBusy}>{deleteBusy?'Suppression…':'Confirmer la suppression'}</button><button type="button" className="button button-dark" disabled={deleteBusy} onClick={()=>{setDeleteOpen(false);setDeletePassword('');setDeleteError('');}}>Annuler</button></div></form>}</section>}
  </main>;
}
