'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, Search } from '../icons';
import { clientApi, productImageUrl } from '../lib/api';
import { invalidateOrderAttempt } from '../cart/idempotency';
import { EmptyCard, PageIntro } from '../ui';

type Option = { id:string; name:string; priceDelta:string; currency:string; linkedProductId:string|null };
type OptionGroup = { id:string; name:string; type:'VARIANT'|'SUPPLEMENT'; required:boolean; minSelections:number; maxSelections:number; options:Option[] };
type Dish = { id:string; name:string; description:string|null; imageUrl:string|null; remaining:number; price:{amount:string;currency:string}; variants:string[]|null; optionGroups?:OptionGroup[] };
type Menu = { businessDate:string; serviceCode:string; imageUrl:string|null; menuVersionId:string; items:Dish[] };
type Selection = { groupId:string; optionIds:string[] };
type CartLine = { lineId:string; productId:string; name:string; quantity:number; price:{amount:string;currency:string}; variant?:string; optionSelections:Selection[]; variantLabel?:string; supplementsLabel?:string; unitEstimate:number };

export default function MenuPage() {
 const params=useSearchParams();const [menu,setMenu]=useState<Menu|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState(params.get('category')??'');const [added,setAdded]=useState('');const [active,setActive]=useState<Dish|null>(null);const [variant,setVariant]=useState('');const [selected,setSelected]=useState<Record<string,string[]>>({});
 useEffect(()=>{clientApi<Menu|null>('menus/public').then(setMenu).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const products=useMemo(()=>menu?.items.filter(item=>item.name.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')))??[],[menu,query]);
 const categories=['Repas','Petit-déjeuner','Snacks','Boissons'];
 function start(item:Dish){if(item.variants?.length||item.optionGroups?.length){setActive(item);setVariant('');setSelected({});return;}add(item,'',[]);}
 function add(item:Dish,chosenVariant:string,selections:Selection[]){
   let cart:CartLine[]=[];try{cart=JSON.parse(localStorage.getItem('jami_cart')??'[]') as CartLine[];}catch{}
   const labels:string[]=[];let extra=0;for(const selection of selections){const group=item.optionGroups?.find(g=>g.id===selection.groupId);for(const id of selection.optionIds){const option=group?.options.find(o=>o.id===id);if(option){if(group?.type==='VARIANT')labels.push(`${group.name} : ${option.name}`);else{labels.push(`+ ${option.name}`);extra+=Number(option.priceDelta);}}}}
   if(chosenVariant)labels.push(`Accompagnement : ${chosenVariant}`);
   const identity=JSON.stringify([item.id,chosenVariant,[...selections].map(s=>[s.groupId,[...s.optionIds].sort()]).sort()]);const existing=cart.find(line=>line.lineId===identity);
   if(existing)existing.quantity=Math.min(item.remaining,existing.quantity+1);else cart.push({lineId:identity,productId:item.id,name:item.name,quantity:1,price:item.price,variant:chosenVariant||undefined,optionSelections:selections,variantLabel:chosenVariant?`Accompagnement : ${chosenVariant}`:labels.filter(value=>!value.startsWith('+')).join(' · ')||undefined,supplementsLabel:labels.filter(value=>value.startsWith('+')).join(' · ')||undefined,unitEstimate:Number(item.price.amount)+extra});
   localStorage.setItem('jami_cart',JSON.stringify(cart));invalidateOrderAttempt(sessionStorage);setAdded(item.name);window.setTimeout(()=>setAdded(''),2000);setActive(null);
 }
 function toggle(group:OptionGroup,optionId:string){setSelected(current=>{const ids=current[group.id]??[];let next:string[];if(group.maxSelections===1)next=ids.includes(optionId)?[]:[optionId];else next=ids.includes(optionId)?ids.filter(id=>id!==optionId):ids.length<group.maxSelections?[...ids,optionId]:ids;return {...current,[group.id]:next};});}
 const chosenSelections=active?.optionGroups?.map(group=>({groupId:group.id,optionIds:selected[group.id]??[]}))??[];
 const canAdd=!!active&&(!active.variants?.length||!!variant)&&active.optionGroups?.every(g=>(selected[g.id]?.length??0)>=g.minSelections&&(selected[g.id]?.length??0)<=g.maxSelections&&(g.required?!!selected[g.id]?.length:true))!==false;
 const estimated=active?Number(active.price.amount)+chosenSelections.reduce((sum,s)=>sum+s.optionIds.reduce((n,id)=>n+Number(active.optionGroups?.find(g=>g.id===s.groupId)?.options.find(o=>o.id===id)?.priceDelta??0),0),0):0;
 return <main className="page-wrap"><PageIntro eyebrow="LE MENU JAMI FOOD" title="La bonne pause vous attend." description="Les plats et tarifs affichés sont ceux du menu publié par le restaurant."/>{productImageUrl(menu?.imageUrl)&&<img className="menu-cover" src={productImageUrl(menu?.imageUrl)!} alt="Menu du jour JAMI FOOD"/>}<div className="menu-toolbar"><label className="search-box"><Search size={18}/><input type="search" placeholder="Rechercher un plat" aria-label="Rechercher un plat" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="public-badge"><span/>{menu?`${menu.serviceCode} · ${menu.businessDate}`:'Menu du jour'}</span></div><nav className="menu-categories" aria-label="Catégories de menu">{categories.map(category=><button type="button" className={query===category?'selected':''} key={category} onClick={()=>setQuery(query===category?'':category)}>{category}</button>)}</nav>{loading?<p role="status">Chargement du menu publié…</p>:error?<EmptyCard title="Menu indisponible" text={error}/>:!menu?<EmptyCard title="Menu non disponible" text="Le restaurant n’a pas encore publié de menu ou le tarif visiteur n’est pas configuré." action={<Link className="text-link" href="/">Retour à l’accueil <ArrowRight size={16}/></Link>}/>:!products.length?<EmptyCard title="Aucun plat pour cette recherche" text="Essayez un autre nom ou choisissez une catégorie différente."/>:<section className="menu-grid">{products.map(item=><article className="dish-card" key={item.id} onClick={()=>start(item)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')start(item);}}><div className="dish-photo-wrap">{productImageUrl(item.imageUrl)?<img className="dish-image" src={productImageUrl(item.imageUrl)!} alt="" onError={e=>{e.currentTarget.style.display='none';const fallback=e.currentTarget.parentElement?.querySelector<HTMLElement>('.dish-placeholder');if(fallback)fallback.style.display='grid';}}/>:null}<div className="dish-placeholder" aria-hidden="true" style={{display:productImageUrl(item.imageUrl)?'none':'grid'}}>J</div></div><div className="dish-copy"><span className="dish-stock">{item.remaining} disponible{item.remaining>1?'s':''}</span><h2>{item.name}</h2>{item.description&&<p>{item.description}</p>}<div className="dish-bottom"><b>{Number(item.price.amount).toLocaleString('fr-FR')} {item.price.currency}</b><button className="button button-dark" type="button" onClick={e=>{e.stopPropagation();start(item);}}>{item.variants?.length||item.optionGroups?.length?'Personnaliser':'Ajouter'}</button></div></div></article>)}</section>}{added&&<p role="status" className="form-note">{added} ajouté au panier. <Link href="/cart">Voir mon panier</Link></p>}
 {active&&<div className="customize-backdrop" role="presentation" onClick={()=>setActive(null)}><section className="customize-sheet" role="dialog" aria-modal="true" aria-labelledby="customize-title" onClick={e=>e.stopPropagation()}><button className="customize-close" type="button" onClick={()=>setActive(null)} aria-label="Fermer">×</button>{productImageUrl(active.imageUrl)&&<img src={productImageUrl(active.imageUrl)!} alt="" className="customize-photo"/>}<p className="eyebrow">PERSONNALISEZ VOTRE PLAT</p><h2 id="customize-title">{active.name}</h2>{active.description&&<p>{active.description}</p>}<strong>{Number(active.price.amount).toLocaleString('fr-FR')} {active.price.currency}</strong>{!!active.variants?.length&&<fieldset className="choice-group"><legend>Choisissez votre accompagnement</legend>{active.variants!.map(value=><label key={value}><input type="radio" name="variant" checked={variant===value} onChange={()=>setVariant(value)}/><span>{value}</span></label>)}</fieldset>}{active.optionGroups?.map(group=><fieldset className="choice-group" key={group.id}><legend>{group.name}{group.required?' · obligatoire':' · facultatif'} <small>{group.minSelections}–{group.maxSelections} choix</small></legend>{group.options.map(option=><label key={option.id}><input type={group.maxSelections===1?'radio':'checkbox'} name={group.id} checked={(selected[group.id]??[]).includes(option.id)} onChange={()=>toggle(group,option.id)}/><span>{option.name}</span><b>{group.type==='SUPPLEMENT'&&Number(option.priceDelta)>0?`+ ${Number(option.priceDelta).toLocaleString('fr-FR')} ${option.currency}`:'Inclus'}</b></label>)}</fieldset>)}<button className="button button-dark customize-submit" type="button" disabled={!canAdd} onClick={()=>add(active,variant,chosenSelections)}>Ajouter au panier · {estimated.toLocaleString('fr-FR')} {active.price.currency}</button></section></div>}
 </main>;
}
