'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, Search } from '../icons';
import { clientApi, productImageUrl } from '../lib/api';
import { EmptyCard, PageIntro } from '../ui';

type Menu = { businessDate:string; serviceCode:string; items:Array<{id:string;name:string;description:string|null;imageUrl:string|null;remaining:number;price:{amount:string;currency:string};variants:string[]|null}> };
type CartLine={productId:string;name:string;quantity:number;price:{amount:string;currency:string}};
export default function MenuPage() {
 const params=useSearchParams();const [menu,setMenu]=useState<Menu|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState(params.get('category')??'');const [added,setAdded]=useState('');
 useEffect(()=>{clientApi<Menu|null>('menus/public').then(value=>setMenu(value)).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const products=useMemo(()=>menu?.items.filter(item=>item.name.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')))??[],[menu,query]);
 const categories=['Repas','Petit-déjeuner','Snacks','Boissons'];
 function add(item:NonNullable<typeof menu>['items'][number]){let cart:CartLine[]=[];try{cart=JSON.parse(localStorage.getItem('jami_cart')??'[]') as CartLine[];}catch{}const row=cart.find(p=>p.productId===item.id);if(row)row.quantity=Math.min(item.remaining,row.quantity+1);else cart.push({productId:item.id,name:item.name,quantity:1,price:item.price});localStorage.setItem('jami_cart',JSON.stringify(cart));setAdded(item.name);window.setTimeout(()=>setAdded(''),1800);}
 return <main className="page-wrap"><PageIntro eyebrow="LE MENU JAMI FOOD" title="La bonne pause vous attend." description="Les plats et tarifs affichés sont ceux du menu publié par le restaurant."/><div className="menu-toolbar"><label className="search-box"><Search size={18}/><input type="search" placeholder="Rechercher un plat" aria-label="Rechercher un plat" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="public-badge"><span/>{menu?`${menu.serviceCode} · ${menu.businessDate}`:'Menu du jour'}</span></div><nav className="menu-categories" aria-label="Catégories de menu">{categories.map(category=><button type="button" className={query===category?'selected':''} key={category} onClick={()=>setQuery(query===category?'':category)}>{category}</button>)}</nav>{loading?<p role="status">Chargement du menu publié…</p>:error?<EmptyCard title="Menu indisponible" text={error}/>:!menu?<EmptyCard title="Menu non disponible" text="Le restaurant n’a pas encore publié de menu ou le tarif visiteur n’est pas configuré." action={<Link className="text-link" href="/">Retour à l’accueil <ArrowRight size={16}/></Link>}/>:!products.length?<EmptyCard title="Aucun plat pour cette recherche" text="Essayez un autre nom ou choisissez une catégorie différente."/>:<section className="menu-grid">{products.map(item=><article className="dish-card" key={item.id}>{productImageUrl(item.imageUrl)?<img className="dish-image" src={productImageUrl(item.imageUrl)!} alt=""/>:<div className="dish-placeholder" aria-hidden="true">J</div>}<div className="dish-copy"><span className="dish-stock">{item.remaining} disponible{item.remaining>1?'s':''}</span><h2>{item.name}</h2>{item.description&&<p>{item.description}</p>}<div className="dish-bottom"><b>{Number(item.price.amount).toLocaleString('fr-FR')} {item.price.currency}</b><button className="button button-dark" type="button" onClick={()=>add(item)}>Ajouter</button></div></div></article>)}</section>}{added&&<p role="status" className="form-note">{added} ajouté au panier. <Link href="/cart">Voir mon panier</Link></p>}</main>;
}
